<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: February 15th at 9:16pm
 */
namespace Product\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class CategorySchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'name',
  1 => 'id',
);
    public static $column_hash = array (
  'name' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'name',
  1 => 'id',
);

        const schema_class = 'Product\\Model\\CategorySchema';
        const collection_class = 'Product\\Model\\CategoryCollection';
        const model_class = 'Product\\Model\\Category';
        const model_name = 'Category';
        const model_namespace = 'Product\\Model';
        const primary_key = 'id';
        const table = 'product_categories';
        const label = 'Category';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 130,
          'label' => 'Category Name',
          'required' => 1,
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'integer',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'name',
);
        $this->primaryKey      = 'id';
        $this->table           = 'product_categories';
        $this->modelClass      = 'Product\\Model\\Category';
        $this->collectionClass = 'Product\\Model\\CategoryCollection';
        $this->label           = 'Category';
        $this->relations       = array( 
  'category_products' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 1,
      'self_column' => 'id',
      'self_schema' => 'Product\\Model\\CategorySchema',
      'foreign_column' => 'category_id',
      'foreign_schema' => 'Product\\Model\\ProductCategorySchema',
    ),
  'accessor' => 'category_products',
  'where' => NULL,
)),
  'products' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 4,
      'relation_junction' => 'category_products',
      'relation_foreign' => 'product',
    ),
  'accessor' => 'products',
  'where' => NULL,
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Category');
        _('Category Name');
    }

}
