<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: February 15th at 3:26pm
 */
namespace Product\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class ProductTypeSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'product_id',
  1 => 'name',
  2 => 'id',
);
    public static $column_hash = array (
  'product_id' => 1,
  'name' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'product_id',
  1 => 'name',
  2 => 'id',
);

        const schema_class = 'Product\\Model\\ProductTypeSchema';
        const collection_class = 'Product\\Model\\ProductTypeCollection';
        const model_class = 'Product\\Model\\ProductType';
        const model_name = 'ProductType';
        const model_namespace = 'Product\\Model';
        const primary_key = 'id';
        const table = 'product_types';
        const label = 'ProductType';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'product_id' => array( 
      'name' => 'product_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'integer',
          'primary' => NULL,
          'label' => 'Product',
          'renderAs' => 'SelectInput',
          'widgetAttributes' => array( 
            ),
          'refer' => 'Product\\Model\\Product',
        ),
    ),
  'name' => array( 
      'name' => 'name',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 120,
          'required' => true,
          'label' => 'Name',
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'integer',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'product_id',
  'name',
);
        $this->primaryKey      = 'id';
        $this->table           = 'product_types';
        $this->modelClass      = 'Product\\Model\\ProductType';
        $this->collectionClass = 'Product\\Model\\ProductTypeCollection';
        $this->label           = 'ProductType';
        $this->relations       = array( 
  'product' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Product\\Model\\ProductTypeSchema',
      'self_column' => 'product_id',
      'foreign_schema' => 'Product\\Model\\ProductSchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'product',
  'where' => NULL,
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('ProductType');
        _('Product');
        _('Name');
    }

}
