#!/usr/bin/env php
<?php
namespace Phifty\Bootstrap;


function msg($msg) {
    echo "\033[0;32m" . $msg . "\033[0m\n";
}

# options for init phifty
#################################
$phifty_submodule_branch = "feature-cli-init";
$phifty_submodule_target = "phifty";

if( ! file_exists('define.php') ) 
{
    if( count($argv) < 3 || $argv[1] != "init" ) 
    {
        echo "define.php does not exist. please give an application name with init command.\n";
        echo "Usage: \n";
        echo "\tphifty init {{AppName}}\n";
        exit(0);
    }

    list( $script, $command, $name ) = $argv;

    msg( "Creating new website $name ..." );

    # create one define.php
    msg("Generating define.php ...");
    file_put_contents( 'define.php' , <<<"DOC"
<?php 
define( 'PH_APP_NAME' , '$name' );
define( 'PH_ENVIRONMENT' , 'dev' ); // or 'prod'
define( 'PH_DEBUG', true);
define( 'PH_ROOT' , __DIR__ );

DOC
    );



    # ----------- put autoload file
    if( ! file_exists('autoload.php') ) {
        msg('Generating autoload.php ...');
        file_put_contents( 'autoload.php' , <<<"DOC"
<?php
include( __DIR__ . '/$phifty_submodule_target/autoload.php');

DOC
);
    }
    # ----------- put autoload file

    if ( ! file_exists('.git') ) {
        msg( "Initializing .git repository... ");
        system("git init");
    }
    msg( "Initializing git submodule ... " );
    system("git submodule init");


    if( $phifty_submodule_branch ) {
        msg( "Adding phifty ($phifty_submodule_branch) to submodule ... " );
        system("git submodule add --branch $phifty_submodule_branch git@git2.corneltek.com:phifty2.git $phifty_submodule_target");
    } else {
        msg( "Adding phifty to submodule ... " );
        system("git submodule add git@git2.corneltek.com:phifty2.git $phifty_submodule_target");
    }

    msg( "Updating phifty submodule ... " );
    system("git submodule update");

    if( ! file_exists( $phifty_submodule_target ) )
        die("phifty submodule dir not found...");

    msg( "Changing directory into phifty ... " );
    chdir( $phifty_submodule_target );

    msg( "Initializing phifty submodules ... " );
    system("git submodule init");

    msg( "Updating phifty submodules ... " );
    system("git submodule update");

    msg( "Changing directory back to app ... " );
    chdir("..");

    msg( "Making sure phifty is ok ... " );
    system("php $phifty_submodule_target/phifty");

    msg( "Done!" );
}

namespace main;

include('autoload.php');
use \Phifty\Commander;

try {
    $cmd = new Commander();
    $cmd->run();
}
# CliException
catch( Exception $e ) 
{
    die(  $e->getMessage()  );
}


