<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: August 31st at 8:41pm
 */
namespace ProductBundle\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class ProductSubsectionSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'title',
  1 => 'cover_image',
  2 => 'content',
  3 => 'product_id',
  4 => 'id',
);
    public static $column_hash = array (
  'title' => 1,
  'cover_image' => 1,
  'content' => 1,
  'product_id' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'title',
  1 => 'cover_image',
  2 => 'content',
  3 => 'product_id',
  4 => 'id',
);

    const schema_class = 'ProductBundle\\Model\\ProductSubsectionSchema';
    const collection_class = 'ProductBundle\\Model\\ProductSubsectionCollection';
    const model_class = 'ProductBundle\\Model\\ProductSubsection';
    const model_name = 'ProductSubsection';
    const model_namespace = 'ProductBundle\\Model';
    const primary_key = 'id';
    const table = 'product_subsections';
    const label = 'ProductSubsection';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'title' => array( 
      'name' => 'title',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'length' => 64,
              'label' => '子區塊標題',
              'renderAs' => 'TextInput',
              'widgetAttributes' => array( 
                  'size' => 50,
                ),
            ),
          'name' => 'title',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'varchar',
          'isa' => 'str',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'attributeTypes' => array( 
              'primary' => 6,
              'size' => 3,
              'autoIncrement' => 6,
              'immutable' => 6,
              'unique' => 6,
              'null' => 6,
              'notNull' => 6,
              'typeConstraint' => 6,
              'timezone' => 6,
              'renderable' => 6,
              'label' => 0,
              'desc' => 2,
              'comment' => 2,
              'refer' => 2,
              'default' => 0,
              'validator' => 0,
              'validatorArgs' => 0,
              'validValues' => 0,
              'validValueBuilder' => 5,
              'optionValues' => 0,
              'validPairs' => 0,
              'canonicalizer' => 5,
              'virtual' => 6,
              'filter' => 5,
              'inflator' => 5,
              'deflator' => 5,
              'renderAs' => 2,
              'widgetAttributes' => 1,
              'contentType' => 2,
              'primaryField' => 6,
              'length' => 3,
              'decimals' => 3,
            ),
          'length' => 64,
          'label' => '子區塊標題',
          'renderAs' => 'TextInput',
          'widgetAttributes' => array( 
              'size' => 50,
            ),
        ),
    ),
  'cover_image' => array( 
      'name' => 'cover_image',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'length' => 64,
              'label' => '子區塊封面圖',
              'renderAs' => 'ThumbImageFileInput',
              'widgetAttributes' => array( 
                ),
            ),
          'name' => 'cover_image',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'varchar',
          'isa' => 'str',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'attributeTypes' => array( 
              'primary' => 6,
              'size' => 3,
              'autoIncrement' => 6,
              'immutable' => 6,
              'unique' => 6,
              'null' => 6,
              'notNull' => 6,
              'typeConstraint' => 6,
              'timezone' => 6,
              'renderable' => 6,
              'label' => 0,
              'desc' => 2,
              'comment' => 2,
              'refer' => 2,
              'default' => 0,
              'validator' => 0,
              'validatorArgs' => 0,
              'validValues' => 0,
              'validValueBuilder' => 5,
              'optionValues' => 0,
              'validPairs' => 0,
              'canonicalizer' => 5,
              'virtual' => 6,
              'filter' => 5,
              'inflator' => 5,
              'deflator' => 5,
              'renderAs' => 2,
              'widgetAttributes' => 1,
              'contentType' => 2,
              'primaryField' => 6,
              'length' => 3,
              'decimals' => 3,
            ),
          'length' => 64,
          'label' => '子區塊封面圖',
          'renderAs' => 'ThumbImageFileInput',
          'widgetAttributes' => array( 
            ),
        ),
    ),
  'content' => array( 
      'name' => 'content',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'label' => '子區塊內文',
              'renderAs' => 'TextareaInput',
              'widgetAttributes' => array( 
                  'class' => '+=mceEditor',
                  'rows' => 5,
                  'cols' => 50,
                ),
            ),
          'name' => 'content',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'text',
          'isa' => 'str',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'attributeTypes' => array( 
              'primary' => 6,
              'size' => 3,
              'autoIncrement' => 6,
              'immutable' => 6,
              'unique' => 6,
              'null' => 6,
              'notNull' => 6,
              'typeConstraint' => 6,
              'timezone' => 6,
              'renderable' => 6,
              'label' => 0,
              'desc' => 2,
              'comment' => 2,
              'refer' => 2,
              'default' => 0,
              'validator' => 0,
              'validatorArgs' => 0,
              'validValues' => 0,
              'validValueBuilder' => 5,
              'optionValues' => 0,
              'validPairs' => 0,
              'canonicalizer' => 5,
              'virtual' => 6,
              'filter' => 5,
              'inflator' => 5,
              'deflator' => 5,
              'renderAs' => 2,
              'widgetAttributes' => 1,
              'contentType' => 2,
              'primaryField' => 6,
              'length' => 3,
              'decimals' => 3,
            ),
          'label' => '子區塊內文',
          'renderAs' => 'TextareaInput',
          'widgetAttributes' => array( 
              'class' => '+=mceEditor',
              'rows' => 5,
              'cols' => 50,
            ),
        ),
    ),
  'product_id' => array( 
      'name' => 'product_id',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'refer' => 'ProductBundle\\Model\\Product',
            ),
          'name' => 'product_id',
          'primary' => NULL,
          'unsigned' => NULL,
          'type' => 'int',
          'isa' => 'int',
          'notNull' => NULL,
          'enum' => NULL,
          'set' => NULL,
          'attributeTypes' => array( 
              'primary' => 6,
              'size' => 3,
              'autoIncrement' => 6,
              'immutable' => 6,
              'unique' => 6,
              'null' => 6,
              'notNull' => 6,
              'typeConstraint' => 6,
              'timezone' => 6,
              'renderable' => 6,
              'label' => 0,
              'desc' => 2,
              'comment' => 2,
              'refer' => 2,
              'default' => 0,
              'validator' => 0,
              'validatorArgs' => 0,
              'validValues' => 0,
              'validValueBuilder' => 5,
              'optionValues' => 0,
              'validPairs' => 0,
              'canonicalizer' => 5,
              'virtual' => 6,
              'filter' => 5,
              'inflator' => 5,
              'deflator' => 5,
              'renderAs' => 2,
              'widgetAttributes' => 1,
              'contentType' => 2,
              'primaryField' => 6,
              'length' => 3,
              'decimals' => 3,
            ),
          'refer' => 'ProductBundle\\Model\\Product',
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'locales' => NULL,
          'attributes' => array( 
              'autoIncrement' => true,
            ),
          'name' => 'id',
          'primary' => true,
          'unsigned' => NULL,
          'type' => 'int',
          'isa' => 'int',
          'notNull' => true,
          'enum' => NULL,
          'set' => NULL,
          'attributeTypes' => array( 
              'primary' => 6,
              'size' => 3,
              'autoIncrement' => 6,
              'immutable' => 6,
              'unique' => 6,
              'null' => 6,
              'notNull' => 6,
              'typeConstraint' => 6,
              'timezone' => 6,
              'renderable' => 6,
              'label' => 0,
              'desc' => 2,
              'comment' => 2,
              'refer' => 2,
              'default' => 0,
              'validator' => 0,
              'validatorArgs' => 0,
              'validValues' => 0,
              'validValueBuilder' => 5,
              'optionValues' => 0,
              'validPairs' => 0,
              'canonicalizer' => 5,
              'virtual' => 6,
              'filter' => 5,
              'inflator' => 5,
              'deflator' => 5,
              'renderAs' => 2,
              'widgetAttributes' => 1,
              'contentType' => 2,
              'primaryField' => 6,
              'length' => 3,
              'decimals' => 3,
            ),
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'title',
  'cover_image',
  'content',
  'product_id',
);
        $this->primaryKey      = 'id';
        $this->table           = 'product_subsections';
        $this->modelClass      = 'ProductBundle\\Model\\ProductSubsection';
        $this->collectionClass = 'ProductBundle\\Model\\ProductSubsectionCollection';
        $this->label           = 'ProductSubsection';
        $this->relations       = array( 
  'product' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'ProductBundle\\Model\\ProductSubsectionSchema',
      'self_column' => 'product_id',
      'foreign_schema' => 'ProductBundle\\Model\\ProductSchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'product',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('ProductSubsection');
        _('子區塊標題');
        _('子區塊封面圖');
        _('子區塊內文');
    }

}
