<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: July 8th at 6:09pm
 */
namespace OrderBundle\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class OrderSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'sum',
  1 => 'qty',
  2 => 'id',
);
    public static $column_hash = array (
  'sum' => 1,
  'qty' => 1,
  'id' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'sum',
  1 => 'qty',
  2 => 'id',
);

    const schema_class = 'OrderBundle\\Model\\OrderSchema';
    const collection_class = 'OrderBundle\\Model\\OrderCollection';
    const model_class = 'OrderBundle\\Model\\Order';
    const model_name = 'Order';
    const model_namespace = 'OrderBundle\\Model';
    const primary_key = 'id';
    const table = 'orders';
    const label = 'Order';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'sum' => array( 
      'name' => 'sum',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'qty' => array( 
      'name' => 'qty',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'id' => array( 
      'name' => 'id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => true,
          'autoIncrement' => true,
        ),
    ),
);
        $this->columnNames     = array( 
  'id',
  'sum',
  'qty',
);
        $this->primaryKey      = 'id';
        $this->table           = 'orders';
        $this->modelClass      = 'OrderBundle\\Model\\Order';
        $this->collectionClass = 'OrderBundle\\Model\\OrderCollection';
        $this->label           = 'Order';
        $this->relations       = array( 
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('Order');
    }

}
